trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    echo "Installing Angular CLI..."
    npm install -g @angular/cli@17.1.2
    echo "Checking if installation was successful..."
    if not "%ERRORLEVEL%" == "0" (
      echo "Angular CLI installation failed with error %ERRORLEVEL%."
      exit /b %ERRORLEVEL%
    )
    echo "Installation check passed."
    
    echo "Running a simple non-dependent command..."
    echo "This should always run."
    
    echo "Now attempting to verify Angular CLI installation..."
    ng --version
    if not "%ERRORLEVEL%" == "0" (
      echo "Failed to verify Angular CLI installation with error %ERRORLEVEL%."
      exit /b %ERRORLEVEL%
    )
    echo "Angular CLI Version Command Executed Successfully."
  displayName: 'Test Angular CLI Installation'
