trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    echo "Installing Angular CLI..."
    npm install -g @angular/cli@17.1.2
    if not "%ERRORLEVEL%" == "0" (
      echo "Failed to install Angular CLI."
      exit /b %ERRORLEVEL%
    )
    
    echo "Installing npm packages..."
    npm install
    if not "%ERRORLEVEL%" == "0" (
      echo "npm install failed."
      exit /b %ERRORLEVEL%
    )
    
    echo "Building Angular project..."
    ng build --prod --verbose
    if not "%ERRORLEVEL%" == "0" (
      echo "Angular build failed."
      exit /b %ERRORLEVEL%
    )
  displayName: 'Install and Build'

- script: |
    echo "Current directory:"
    pwd
    echo "Listing directory contents:"
    dir
    
    echo "Checking dist directory specifically:"
    dir dist\car-sales /a
  displayName: 'List build artifacts'
  condition: succeededOrFailed()  # Ensures this step runs even if the previous step fails
