trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    echo "Installing Angular CLI..."
    npm install -g @angular/cli@17.1.2
    ng --version
    echo "Angular CLI installed."
    
    echo "Installing npm packages..."
    npm install
    echo "npm packages installed."
    
    echo "Attempting to build Angular project..."
    ng build --prod --verbose
    if not "%ERRORLEVEL%" == "0" (
      echo "Build failed with error %ERRORLEVEL%"
      exit /b %ERRORLEVEL%
    ) else (
      echo "Angular build command executed successfully."
    )
    
    echo "Checking if 'dist/car-sales' directory was created..."
    if exist dist\car-sales (
      echo "Directory 'dist/car-sales' exists."
      dir dist\car-sales
    ) else (
      echo "Directory 'dist/car-sales' does not exist."
    )
  displayName: 'Diagnostic Build Steps'
  failOnStderr: false

- script: |
    echo "Final directory structure check:"
    dir
  displayName: 'Final Directory Check'
