# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@17.1.2
    npm install
    if not "%ERRORLEVEL%" == "0" exit /b %ERRORLEVEL%
    ng build --prod --verbose
    if not "%ERRORLEVEL%" == "0" exit /b %ERRORLEVEL%
  displayName: 'npm install and build'
  failOnStderr: false  # Adjust this based on whether you expect warnings to be treated as errors

- script: |
    echo "Listing contents of current directory:"
    dir
    echo "Listing contents of dist directory:"
    dir dist\car-sales
  displayName: 'List build artifacts'
  condition: succeededOrFailed()  # This ensures the step runs regardless of the previous step's status

