trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    echo "Installing Angular CLI..."
    npm install -g @angular/cli@17.1.2
    echo "Angular CLI installed."

    echo "Installing npm packages..."
    npm install
    echo "npm packages installed."
    
    echo "Attempting to build Angular project..."
    ng build --prod --verbose
    echo "Angular build command executed."
    
    echo "Checking if 'dist/car-sales' directory was created..."
    dir dist\car-sales
  displayName: 'Diagnostic Build Steps'
  failOnStderr: false

- script: |
    echo "Final directory structure check:"
    dir
  displayName: 'Final Directory Check'
