trigger:
- master

pool:
  name: my-personal-computer

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.11.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@17.1.2
  displayName: 'install angular/cli'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    ng build
  displayName: 'ng build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'dist'
    publishLocation: 'Container'

# - task: PublishPipelineArtifact@0
#   inputs:
#     targetPath: '$(agent.builddirectory)/s/dist'
#     artifactName: 'dist'
#   displayName: 'Publish Pipeline Artifact: dist'